spring:
  application:
    name: notification-service

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    fetch-registry: true
    register-with-eureka: true

