services:

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - bletflix-db
    networks:
      - postgres

  auth-service:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - postgres

  notification-service:
    container_name: notification-service
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - postgres

  posts-service:
    container_name: posts-service
    build: ./posts-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - postgres

  subscr-service:
    container_name: subscr-service
    build: ./subscr-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - postgres

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      - postgres

  video-service:
    container_name: video-service
    build: ./video-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server

  bletflix-db:
    container_name: bletflix-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminka
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - bletflix-db
networks:
  postgres:
    driver: bridge


volumes:
  postgres:
  pgadmin: