services:
  eureka-server:
    image: bletflix/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - bletflix-db
    networks:
      - postgres
    restart: unless-stopped

  auth-service:
    image: bletflix/auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - postgres
    depends_on:
      - eureka-server
    restart: unless-stopped

  notification-service:
    image: bletflix/notification-service:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    networks:
      - postgres
    depends_on:
      - eureka-server
    restart: unless-stopped

  posts-service:
    image: bletflix/posts-service:latest
    container_name: posts-service
    ports:
      - "8083:8083"
    networks:
      - postgres
    depends_on:
      - eureka-server
    restart: unless-stopped

  subscr-service:
    image: bletflix/subscr-service:latest
    container_name: subscr-service
    ports:
      - "8084:8084"
    networks:
      - postgres
    depends_on:
      - eureka-server
    restart: unless-stopped

  user-service:
    image: bletflix/user-service:latest
    container_name: user-service
    ports:
      - "8085:8085"
    networks:
      - postgres
    depends_on:
      - eureka-server
    restart: unless-stopped

  video-service:
    image: bletflix/video-service:latest
    container_name: video-service
    ports:
      - "8086:8086"
    networks:
      - postgres
    depends_on:
      - eureka-server
    restart: unless-stopped

  bletflix-db:
    container_name: bletflix-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminka
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge


volumes:
  postgres:
  pgadmin: