spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:config-server
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true


