server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/warneverchange/bletflix-config-repo
          clone-on-start: true
      allow-override: true
